- negotiation:
    deadline: 2 # seconds
    parties:
    - party: parties/learningagent-1.6.0-jar-with-dependencies.jar
      profile: profiles/fitness/fitness1.json
      parameters: {}
    - party: parties/randomparty-1.6.0-jar-with-dependencies.jar
      profile: profiles/fitness/fitness2.json
- negotiation:
    deadline: 2
    parties:
    - party: parties/learningagent-1.6.0-jar-with-dependencies.jar
      profile: profiles/flightbooking/flightbooking1.json
      parameters: {}
    - party: parties/randomparty-1.6.0-jar-with-dependencies.jar
      profile: profiles/flightbooking/flightbooking2.json
- negotiation:
    deadline: 2
    parties:
    - party: parties/learningagent-1.6.0-jar-with-dependencies.jar
      profile: profiles/japantrip/japantrip1.json
      parameters: {}
    - party: parties/randomparty-1.6.0-jar-with-dependencies.jar
      profile: profiles/japantrip/japantrip2.json
- learn:
    deadline: 2
    parties:
    - party: parties/learningagent-1.6.0-jar-with-dependencies.jar
- negotiation:
    deadline: 2
    parties:
    - party: parties/learningagent-1.6.0-jar-with-dependencies.jar
      profile: profiles/jobs/jobs1.json
      parameters: {}
    - party: parties/randomparty-1.6.0-jar-with-dependencies.jar
      profile: profiles/jobs/jobs2.json
- negotiation:
    deadline: 2
    parties:
    - party: parties/learningagent-1.6.0-jar-with-dependencies.jar
      profile: profiles/laptop/laptopBuyer.json
      parameters: {}
    - party: parties/randomparty-1.6.0-jar-with-dependencies.jar
      profile: profiles/laptop/laptopSeller.json
- learn:
    deadline: 2
    parties:
    - party: parties/learningagent-1.6.0-jar-with-dependencies.jar